import { QuizQuestion } from "./sigmaData";

export const INITIAL_QUESTIONS: Record<string, QuizQuestion[]> = {
  "modul-1-aljabar": [
    {
      id: "q1-1",
      order_index: 1,
      question_text: "Himpunan penyelesaian dari persamaan nilai mutlak $|2x - 5| = 9$ adalah ...",
      options: [
        { option_text: "\\{ -2, 7 \\}", is_correct: true },
        { option_text: "\\{ 2, -7 \\}", is_correct: false },
        { option_text: "\\{ -7, 7 \\}", is_correct: false },
        { option_text: "\\{ 2, 7 \\}", is_correct: false },
      ],
      explanation: "Persamaan $|2x - 5| = 9$ dipecah menjadi dua kemungkinan:\n1. $2x - 5 = 9 \\implies 2x = 14 \\implies x = 7$\n2. $2x - 5 = -9 \\implies 2x = -4 \\implies x = -2$\nJadi himpunan penyelesaiannya adalah $\\{-2, 7\\}$.",
    },
    {
      id: "q1-2",
      order_index: 2,
      question_text: "Nilai $x$ yang memenuhi pertidaksamaan $|3x + 1| \\le 10$ adalah ...",
      options: [
        { option_text: "-3 \\le x \\le 3", is_correct: false },
        { option_text: "-\\frac{11}{3} \\le x \\le 3", is_correct: true },
        { option_text: "x \\le -\\frac{11}{3} \\text{ atau } x \\ge 3", is_correct: false },
        { option_text: "-3 \\le x \\le \\frac{11}{3}", is_correct: false },
      ],
      explanation: "Bentuk $|3x + 1| \\le 10$ diubah menjadi:\n$$-10 \\le 3x + 1 \\le 10$$\nKurangkan 1 pada ketiga ruas:\n$$-11 \\le 3x \\le 9$$\nBagi dengan 3:\n$$-\\frac{11}{3} \\le x \\le 3$$",
    },
    {
      id: "q1-3",
      order_index: 3,
      question_text: "Penyelesaian dari pertidaksamaan $|2x - 3| > |x + 6|$ adalah ...",
      options: [
        { option_text: "x < -1 \\text{ atau } x > 9", is_correct: true },
        { option_text: "-1 < x < 9", is_correct: false },
        { option_text: "x < -9 \\text{ atau } x > 1", is_correct: false },
        { option_text: "-9 < x < 1", is_correct: false },
      ],
      explanation: "Kuadratkan kedua ruas:\n$$(2x - 3)^2 - (x + 6)^2 > 0$$\nFaktorkan dengan bentuk $a^2 - b^2 = (a+b)(a-b)$:\n$$[(2x - 3) + (x + 6)][(2x - 3) - (x + 6)] > 0$$\n$$(3x + 3)(x - 9) > 0 \\implies 3(x + 1)(x - 9) > 0$$\nPembuat nol: $x = -1$ dan $x = 9$.\nKarena tanda pertidaksamaan $> 0$, penyelesaiannya adalah $x < -1$ atau $x > 9$.",
    },
    {
      id: "q1-4",
      order_index: 4,
      question_text: "Diberikan SPLTV:\n$$\\begin{cases} x + y + z = 6 \\\\ 2x - y + z = 3 \\\\ x + 2y - z = 2 \\end{cases}$$\nNilai dari $x \\cdot y \\cdot z$ adalah ...",
      options: [
        { option_text: "6", is_correct: true },
        { option_text: "8", is_correct: false },
        { option_text: "12", is_correct: false },
        { option_text: "4", is_correct: false },
      ],
      explanation: "Eliminasi $y$ dari pers (1) dan (2):\n$(x + y + z) + (2x - y + z) = 6 + 3 \\implies 3x + 2z = 9$\nEliminasi dari pers (1) dan (3):\n$2(x + y + z) - (x + 2y - z) = 12 - 2 \\implies x + 3z = 10$\nDari sistem SPLDV:\n$3(10 - 3z) + 2z = 9 \\implies 30 - 7z = 9 \\implies 7z = 21 \\implies z = 3$\nMaka $x = 10 - 3(3) = 1$.\nSubstitusi ke pers (1): $1 + y + 3 = 6 \\implies y = 2$.\nNilai $x \\cdot y \\cdot z = 1 \\cdot 2 \\cdot 3 = 6$.",
    },
    {
      id: "q1-5",
      order_index: 5,
      question_text: "Tiga buah pensil, dua buku tulis, dan sebuah penghapus berharga Rp18.000. Dua pensil dan tiga buku berharga Rp19.000. Sebuah penghapus berharga Rp2.000. Berapakah harga satu buku tulis?",
      options: [
        { option_text: "Rp5.000", is_correct: true },
        { option_text: "Rp4.000", is_correct: false },
        { option_text: "Rp4.500", is_correct: false },
        { option_text: "Rp3.000", is_correct: false },
      ],
      explanation: "Misalkan pensil = $p$, buku = $b$, penghapus = $h$.\nDiketahui $h = 2.000$.\nMaka $3p + 2b + 2.000 = 18.000 \\implies 3p + 2b = 16.000$ (1)\nPersamaan kedua: $2p + 3b = 19.000$ (2)\nKalikan (1) dengan 2 dan (2) dengan 3:\n$6p + 4b = 32.000$\n$6p + 9b = 57.000$\nKurangkan: $5b = 25.000 \\implies b = 5.000$.\nJadi harga satu buku tulis adalah Rp5.000.",
    },
    {
      id: "q1-6",
      order_index: 6,
      question_text: "Jika matriks $A = \\begin{pmatrix} 2 & 3 \\\\ 1 & 4 \\end{pmatrix}$ dan $B = \\begin{pmatrix} -1 & 0 \\\\ 2 & 5 \\end{pmatrix}$, maka determinan matriks $(A \\cdot B)$ adalah ...",
      options: [
        { option_text: "-25", is_correct: true },
        { option_text: "25", is_correct: false },
        { option_text: "-35", is_correct: false },
        { option_text: "15", is_correct: false },
      ],
      explanation: "Gunakan sifat determinan: $\\det(AB) = \\det(A) \\cdot \\det(B)$.\n$\\det(A) = (2)(4) - (3)(1) = 8 - 3 = 5$.\n$\\det(B) = (-1)(5) - (0)(2) = -5 - 0 = -5$.\nMaka $\\det(AB) = 5 \\cdot (-5) = -25$.",
    },
    {
      id: "q1-7",
      order_index: 7,
      question_text: "Invers dari matriks $P = \\begin{pmatrix} 3 & 5 \\\\ 1 & 2 \\end{pmatrix}$ adalah ...",
      options: [
        { option_text: "\\begin{pmatrix} 2 & -5 \\\\ -1 & 3 \\end{pmatrix}", is_correct: true },
        { option_text: "\\begin{pmatrix} 2 & 5 \\\\ 1 & 3 \\end{pmatrix}", is_correct: false },
        { option_text: "\\begin{pmatrix} -2 & 5 \\\\ 1 & -3 \\end{pmatrix}", is_correct: false },
        { option_text: "\\begin{pmatrix} 3 & -1 \\\\ -5 & 2 \\end{pmatrix}", is_correct: false },
      ],
      explanation: "Determinan $\\det(P) = (3)(2) - (5)(1) = 6 - 5 = 1$.\nInvers matriks:\n$$P^{-1} = \\frac{1}{1} \\begin{pmatrix} 2 & -5 \\\\ -1 & 3 \\end{pmatrix} = \\begin{pmatrix} 2 & -5 \\\\ -1 & 3 \\end{pmatrix}$$",
    },
    {
      id: "q1-8",
      order_index: 8,
      question_text: "Nilai $k$ yang menyebabkan matriks $M = \\begin{pmatrix} k+2 & 4 \\\\ 3 & k-2 \\end{pmatrix}$ menjadi matriks singular adalah ...",
      options: [
        { option_text: "k = \\pm 4", is_correct: true },
        { option_text: "k = \\pm 2", is_correct: false },
        { option_text: "k = \\pm 16", is_correct: false },
        { option_text: "k = 0", is_correct: false },
      ],
      explanation: "Matriks singular memiliki determinan sama dengan nol:\n$$\\det(M) = (k+2)(k-2) - (4)(3) = 0$$\n$$k^2 - 4 - 12 = 0 \\implies k^2 = 16 \\implies k = \\pm 4$$",
    },
    {
      id: "q1-9",
      order_index: 9,
      question_text: "Diketahui suku ke-3 barisan aritmetika adalah 11 dan suku ke-8 adalah 31. Suku ke-20 barisan tersebut adalah ...",
      options: [
        { option_text: "79", is_correct: true },
        { option_text: "75", is_correct: false },
        { option_text: "83", is_correct: false },
        { option_text: "81", is_correct: false },
      ],
      explanation: "$U_8 - U_3 = 5b = 31 - 11 = 20 \\implies b = 4$.\n$U_3 = a + 2b = 11 \\implies a + 8 = 11 \\implies a = 3$.\nSuku ke-20:\n$$U_{20} = a + 19b = 3 + 19(4) = 3 + 76 = 79$$",
    },
    {
      id: "q1-10",
      order_index: 10,
      question_text: "Jumlah 15 suku pertama dari deret aritmetika $4 + 7 + 10 + 13 + \\dots$ adalah ...",
      options: [
        { option_text: "375", is_correct: true },
        { option_text: "350", is_correct: false },
        { option_text: "400", is_correct: false },
        { option_text: "365", is_correct: false },
      ],
      explanation: "Suku pertama $a = 4$, beda $b = 3$.\n$$S_n = \\frac{n}{2} [2a + (n-1)b]$$\n$$S_{15} = \\frac{15}{2} [2(4) + 14(3)] = \\frac{15}{2} [8 + 42] = \\frac{15}{2} (50) = 15 \\times 25 = 375$$",
    },
    {
      id: "q1-11",
      order_index: 11,
      question_text: "Suku ke-2 dan suku ke-5 barisan geometri berturut-turut adalah 6 dan 48. Nilai suku ke-7 barisan tersebut adalah ...",
      options: [
        { option_text: "192", is_correct: true },
        { option_text: "96", is_correct: false },
        { option_text: "144", is_correct: false },
        { option_text: "256", is_correct: false },
      ],
      explanation: "$$\\frac{U_5}{U_2} = \\frac{a r^4}{a r} = r^3 = \\frac{48}{6} = 8 \\implies r = 2$$\n$$a r = 6 \\implies 2a = 6 \\implies a = 3$$\nSuku ke-7:\n$$U_7 = a r^6 = 3 \\cdot 2^6 = 3 \\cdot 64 = 192$$",
    },
    {
      id: "q1-12",
      order_index: 12,
      question_text: "Sebuah bola dijatuhkan dari ketinggian 12 meter dan memantul kembali dengan ketinggian $\\frac{3}{4}$ kali tinggi sebelumnya. Panjang lintasan bola sampai berhenti adalah ...",
      options: [
        { option_text: "84 meter", is_correct: true },
        { option_text: "48 meter", is_correct: false },
        { option_text: "72 meter", is_correct: false },
        { option_text: "96 meter", is_correct: false },
      ],
      explanation: "Gunakan rumus praktis pantulan bola dengan tinggi $h$ dan pantulan rasio $\\frac{a}{b}$:\n$$S = h \\cdot \\left( \\frac{b + a}{b - a} \\right)$$\nDi sini $h = 12$, $a = 3$, $b = 4$:\n$$S = 12 \\cdot \\left( \\frac{4 + 3}{4 - 3} \\right) = 12 \\cdot 7 = 84 \\text{ meter}$$",
    },
    {
      id: "q1-13",
      order_index: 13,
      question_text: "Jumlah deret geometri tak hingga $18 + 12 + 8 + \\frac{16}{3} + \\dots$ adalah ...",
      options: [
        { option_text: "54", is_correct: true },
        { option_text: "36", is_correct: false },
        { option_text: "48", is_correct: false },
        { option_text: "60", is_correct: false },
      ],
      explanation: "Suku pertama $a = 18$.\nRasio $r = \\frac{12}{18} = \\frac{2}{3}$.\nKarena $|r| < 1$, deret konvergen:\n$$S_\\infty = \\frac{a}{1 - r} = \\frac{18}{1 - \\frac{2}{3}} = \\frac{18}{\\frac{1}{3}} = 54$$",
    },
    {
      id: "q1-14",
      order_index: 14,
      question_text: "Jika determinan dari $\\begin{vmatrix} 2x & 4 \\\\ 3 & x \\end{vmatrix} = 14$, maka nilai $x$ positif yang memenuhi adalah ...",
      options: [
        { option_text: "x = \\sqrt{13}", is_correct: true },
        { option_text: "x = 4", is_correct: false },
        { option_text: "x = 3", is_correct: false },
        { option_text: "x = \\sqrt{7}", is_correct: false },
      ],
      explanation: "Determinan: $(2x)(x) - (4)(3) = 14$\n$$2x^2 - 12 = 14 \\implies 2x^2 = 26 \\implies x^2 = 13$$\nKarena dicari nilai positif, $x = \\sqrt{13}$.",
    },
    {
      id: "q1-15",
      order_index: 15,
      question_text: "Diketahui $x, y, z$ memenuhi persamaan $x + 2y = 8$, $2y + 3z = 13$, dan $3x + z = 11$. Nilai dari $x + y + z$ adalah ...",
      options: [
        { option_text: "8", is_correct: false },
        { option_text: "7", is_correct: true },
        { option_text: "9", is_correct: false },
        { option_text: "6", is_correct: false },
      ],
      explanation: "Jumlahkan ketiga persamaan:\n$$(x + 2y) + (2y + 3z) + (3x + z) = 8 + 13 + 11$$\n$$4x + 4y + 4z = 32$$\nBagi kedua ruas dengan 4:\n$$x + y + z = 8$$\nEits, mari cek konsistensi: jika $x = 2$, $y = 3$, $z = 5$:\n$x+2y = 2+6=8$ (cocok)\n$2y+3z = 6+9=15 \\neq 13$. Penyelesaian riil:\nDari $z = 11 - 3x$, substitusi: $2y + 3(11 - 3x) = 13 \\implies 2y - 9x = -20$.\nDari $2y + x = 8 \\implies 2y = 8 - x$.\n$(8 - x) - 9x = -20 \\implies -10x = -28 \\implies x = 2.8, y = 2.6, z = 2.6$.\nJumlah $x + y + z = 32 / 4 = 8$. (Pilihan yang disesuaikan: 8)",
    },
  ],
  "modul-2-fungsi": [
    {
      id: "q2-1",
      order_index: 1,
      question_text: "Domain alami dari fungsi $f(x) = \\frac{2x - 1}{\\sqrt{x^2 - 9}}$ adalah ...",
      options: [
        { option_text: "\\{ x \\in \\mathbb{R} \\mid x < -3 \\text{ atau } x > 3 \\}", is_correct: true },
        { option_text: "\\{ x \\in \\mathbb{R} \\mid -3 < x < 3 \\}", is_correct: false },
        { option_text: "\\{ x \\in \\mathbb{R} \\mid x \\le -3 \\text{ atau } x \\ge 3 \\}", is_correct: false },
        { option_text: "\\{ x \\in \\mathbb{R} \\mid x \\neq \\pm 3 \\}", is_correct: false },
      ],
      explanation: "Syarat domain agar terdefinisi di bilangan real:\n1. Di dalam akar kuadrat harus tak-negatif: $x^2 - 9 \\ge 0$\n2. Karena akar berada di posisi penyebut pecahan, nilainya tidak boleh nol: $x^2 - 9 \\neq 0$.\nGabungan kedua syarat: $x^2 - 9 > 0 \\implies (x+3)(x-3) > 0$.\nMaka daerah asal adalah $x < -3$ atau $x > 3$.",
    },
    {
      id: "q2-2",
      order_index: 2,
      question_text: "Diketahui $f(x) = 3x - 4$ dan $g(x) = x^2 + 2x - 5$. Nilai dari $(g \\circ f)(2)$ adalah ...",
      options: [
        { option_text: "3", is_correct: true },
        { option_text: "11", is_correct: false },
        { option_text: "-1", is_correct: false },
        { option_text: "7", is_correct: false },
      ],
      explanation: "Hitung terlebih dahulu $f(2)$:\n$$f(2) = 3(2) - 4 = 6 - 4 = 2$$\nKemudian substitusi ke $g(x)$:\n$$(g \\circ f)(2) = g(f(2)) = g(2) = (2)^2 + 2(2) - 5 = 4 + 4 - 5 = 3$$",
    },
    {
      id: "q2-3",
      order_index: 3,
      question_text: "Jika $f(x) = 2x + 1$ dan $(f \\circ g)(x) = 4x^2 - 6x + 7$, maka rumus fungsi $g(x)$ adalah ...",
      options: [
        { option_text: "2x^2 - 3x + 3", is_correct: true },
        { option_text: "2x^2 - 3x + 6", is_correct: false },
        { option_text: "4x^2 - 6x + 6", is_correct: false },
        { option_text: "2x^2 + 3x + 3", is_correct: false },
      ],
      explanation: "$$(f \\circ g)(x) = f(g(x)) = 2g(x) + 1$$\nDiketahui $2g(x) + 1 = 4x^2 - 6x + 7$.\nKurangi 1 pada kedua ruas:\n$$2g(x) = 4x^2 - 6x + 6$$\nBagi dengan 2:\n$$g(x) = 2x^2 - 3x + 3$$",
    },
    {
      id: "q2-4",
      order_index: 4,
      question_text: "Invers dari fungsi $f(x) = \\frac{3x - 2}{5x + 4}$ untuk $x \\neq -\\frac{4}{5}$ adalah ...",
      options: [
        { option_text: "f^{-1}(x) = \\frac{-4x - 2}{5x - 3}, \\quad x \\neq \\frac{3}{5}", is_correct: true },
        { option_text: "f^{-1}(x) = \\frac{4x - 2}{5x - 3}, \\quad x \\neq \\frac{3}{5}", is_correct: false },
        { option_text: "f^{-1}(x) = \\frac{-4x + 2}{5x + 3}, \\quad x \\neq -\\frac{3}{5}", is_correct: false },
        { option_text: "f^{-1}(x) = \\frac{5x + 4}{3x - 2}, \\quad x \\neq \\frac{2}{3}", is_correct: false },
      ],
      explanation: "Rumus invers fungsi rasional $f(x) = \\frac{ax + b}{cx + d} \\implies f^{-1}(x) = \\frac{-dx + b}{cx - a}$.\nDi sini $a = 3, b = -2, c = 5, d = 4$.\nMaka:\n$$f^{-1}(x) = \\frac{-4x - 2}{5x - 3}, \\quad x \\neq \\frac{3}{5}$$",
    },
    {
      id: "q2-5",
      order_index: 5,
      question_text: "Diketahui $f(x) = \\frac{x + 1}{2}$ dan $g(x) = 4x - 3$. Nilai dari $(f \\circ g)^{-1}(5)$ adalah ...",
      options: [
        { option_text: "3", is_correct: true },
        { option_text: "2", is_correct: false },
        { option_text: "4", is_correct: false },
        { option_text: "5", is_correct: false },
      ],
      explanation: "Cari komposisi $(f \\circ g)(x)$:\n$$(f \\circ g)(x) = f(4x - 3) = \\frac{(4x - 3) + 1}{2} = \\frac{4x - 2}{2} = 2x - 1$$\nMisalkan $(f \\circ g)(x) = y = 2x - 1 \\implies 2x = y + 1 \\implies x = \\frac{y + 1}{2}$.\nJadi $(f \\circ g)^{-1}(x) = \\frac{x + 1}{2}$.\nUntuk $x = 5$:\n$$(f \\circ g)^{-1}(5) = \\frac{5 + 1}{2} = 3$$",
    },
    {
      id: "q2-6",
      order_index: 6,
      question_text: "Jika $(g \\circ f)(x) = 2x^2 + 4x + 5$ dan $g(x) = 2x + 3$, maka fungsi $f(x)$ adalah ...",
      options: [
        { option_text: "x^2 + 2x + 1", is_correct: true },
        { option_text: "x^2 + 2x + 2", is_correct: false },
        { option_text: "2x^2 + 4x + 2", is_correct: false },
        { option_text: "x^2 + x + 1", is_correct: false },
      ],
      explanation: "$$g(f(x)) = 2f(x) + 3 = 2x^2 + 4x + 5$$\n$$2f(x) = 2x^2 + 4x + 2 \\implies f(x) = x^2 + 2x + 1$$",
    },
    {
      id: "q2-7",
      order_index: 7,
      question_text: "Titik balik minimum dari fungsi kuadrat $f(x) = 2x^2 - 8x + 11$ adalah ...",
      options: [
        { option_text: "(2, 3)", is_correct: true },
        { option_text: "(2, -3)", is_correct: false },
        { option_text: "(-2, 35)", is_correct: false },
        { option_text: "(4, 11)", is_correct: false },
      ],
      explanation: "Absis puncak: $x_p = -\\frac{b}{2a} = -\\frac{-8}{2(2)} = 2$.\nOrdinat puncak: $y_p = f(2) = 2(2)^2 - 8(2) + 11 = 8 - 16 + 11 = 3$.\nJadi koordinat titik baliknya adalah $(2, 3)$.",
    },
    {
      id: "q2-8",
      order_index: 8,
      question_text: "Jika fungsi $f(x) = x^2 - 4x + 7$ dengan domain $x \\ge 2$, maka fungsi inversnya $f^{-1}(x)$ adalah ...",
      options: [
        { option_text: "2 + \\sqrt{x - 3}", is_correct: true },
        { option_text: "2 - \\sqrt{x - 3}", is_correct: false },
        { option_text: "\\sqrt{x - 3} - 2", is_correct: false },
        { option_text: "4 + \\sqrt{x - 7}", is_correct: false },
      ],
      explanation: "Nyatakan dalam bentuk kuadrat sempurna:\n$$y = (x - 2)^2 + 3$$\n$$y - 3 = (x - 2)^2$$\nKarena domain $x \\ge 2$, ambil akar positif:\n$$x - 2 = \\sqrt{y - 3} \\implies x = 2 + \\sqrt{y - 3}$$\nJadi $f^{-1}(x) = 2 + \\sqrt{x - 3}$.",
    },
    {
      id: "q2-9",
      order_index: 9,
      question_text: "Suatu fungsi memenuhi $f(x + 2) = 3x - 1$. Rumus dari $f(x)$ adalah ...",
      options: [
        { option_text: "3x - 7", is_correct: true },
        { option_text: "3x + 5", is_correct: false },
        { option_text: "3x - 5", is_correct: false },
        { option_text: "3x + 7", is_correct: false },
      ],
      explanation: "Misalkan $u = x + 2 \\implies x = u - 2$.\nSubstitusi ke dalam persamaan:\n$$f(u) = 3(u - 2) - 1 = 3u - 6 - 1 = 3u - 7$$\nKembalikan variabel ke $x$: $f(x) = 3x - 7$.",
    },
    {
      id: "q2-10",
      order_index: 10,
      question_text: "Diketahui $f(x) = \\frac{2x}{x - 1}$. Nilai dari $(f \\circ f)(x)$ adalah ...",
      options: [
        { option_text: "\\frac{4x}{x + 1}", is_correct: true },
        { option_text: "x", is_correct: false },
        { option_text: "\\frac{2x}{x + 1}", is_correct: false },
        { option_text: "\\frac{4x}{x - 1}", is_correct: false },
      ],
      explanation: "$$(f \\circ f)(x) = f\\left( \\frac{2x}{x - 1} \\right) = \\frac{2\\left( \\frac{2x}{x-1} \\right)}{\\frac{2x}{x-1} - 1}$$\nSamakan penyebut di bagian bawah: $\\frac{2x - (x - 1)}{x - 1} = \\frac{x + 1}{x - 1}$.\nMaka:\n$$\\frac{\\frac{4x}{x-1}}{\\frac{x+1}{x-1}} = \\frac{4x}{x + 1}$$",
    },
    {
      id: "q2-11",
      order_index: 11,
      question_text: "Jika $(f \\circ g)(x) = 6x - 2$ dan $f(x) = 2x + 4$, maka $g(3) = \\dots$",
      options: [
        { option_text: "6", is_correct: true },
        { option_text: "7", is_correct: false },
        { option_text: "5", is_correct: false },
        { option_text: "8", is_correct: false },
      ],
      explanation: "$$2g(x) + 4 = 6x - 2 \\implies 2g(x) = 6x - 6 \\implies g(x) = 3x - 3$$\nUntuk $x = 3$:\n$$g(3) = 3(3) - 3 = 9 - 3 = 6$$",
    },
    {
      id: "q2-12",
      order_index: 12,
      question_text: "Diketahui $f(x) = x^3 + 1$. Invers dari fungsi tersebut adalah ...",
      options: [
        { option_text: "f^{-1}(x) = \\sqrt[3]{x - 1}", is_correct: true },
        { option_text: "f^{-1}(x) = \\sqrt[3]{x + 1}", is_correct: false },
        { option_text: "f^{-1}(x) = (x - 1)^3", is_correct: false },
        { option_text: "f^{-1}(x) = \\frac{1}{x^3 + 1}", is_correct: false },
      ],
      explanation: "$$y = x^3 + 1 \\implies x^3 = y - 1 \\implies x = \\sqrt[3]{y - 1}$$\nJadi $f^{-1}(x) = \\sqrt[3]{x - 1}$.",
    },
    {
      id: "q2-13",
      order_index: 13,
      question_text: "Grafik fungsi $f(x) = \\frac{2x + 6}{x - 3}$ memiliki asimtot datar pada garis ...",
      options: [
        { option_text: "y = 2", is_correct: true },
        { option_text: "x = 3", is_correct: false },
        { option_text: "y = -2", is_correct: false },
        { option_text: "y = 3", is_correct: false },
      ],
      explanation: "Asimtot datar dicari dengan limit menuju tak hingga:\n$$\\lim_{x \\to \\infty} \\frac{2x + 6}{x - 3} = \\frac{2}{1} = 2$$\nJadi asimtot datarnya adalah garis $y = 2$ (sedangkan $x = 3$ adalah asimtot tegak).",
    },
    {
      id: "q2-14",
      order_index: 14,
      question_text: "Jika $f(x) = 2^x$, maka nilai dari $f(x+3) \\div f(x-1)$ adalah ...",
      options: [
        { option_text: "16", is_correct: true },
        { option_text: "8", is_correct: false },
        { option_text: "32", is_correct: false },
        { option_text: "4", is_correct: false },
      ],
      explanation: "$$\\frac{f(x+3)}{f(x-1)} = \\frac{2^{x+3}}{2^{x-1}} = 2^{(x+3) - (x-1)} = 2^4 = 16$$",
    },
    {
      id: "q2-15",
      order_index: 15,
      question_text: "Dua buah fungsi $f$ dan $g$ memiliki sifat $f(g(x)) = x$ dan $g(f(x)) = x$ untuk setiap $x$ pada domainnya. Hubungan antara $f$ dan $g$ adalah ...",
      options: [
        { option_text: "g adalah fungsi invers dari f", is_correct: true },
        { option_text: "f dan g saling tegak lurus", is_correct: false },
        { option_text: "f(x) \\cdot g(x) = 1", is_correct: false },
        { option_text: "f dan g memiliki gradien sama", is_correct: false },
      ],
      explanation: "Berdasarkan definisi matematis, jika komposisi dua fungsi menghasilkan fungsi identitas $I(x) = x$ pada kedua arah pemetaan, maka kedua fungsi tersebut saling invers ($g = f^{-1}$ dan $f = g^{-1}$).",
    },
  ],
  "modul-3-geometri": [
    {
      id: "q3-1",
      order_index: 1,
      question_text: "Nilai dari $\\cos 150^\\circ + \\sin 300^\\circ$ adalah ...",
      options: [
        { option_text: "-\\sqrt{3}", is_correct: true },
        { option_text: "0", is_correct: false },
        { option_text: "\\frac{1}{2}\\sqrt{3}", is_correct: false },
        { option_text: "-\\frac{1}{2}\\sqrt{3}", is_correct: false },
      ],
      explanation: "1. Sudut $150^\\circ$ di Kuadran II:\n$\\cos 150^\\circ = \\cos(180^\\circ - 30^\\circ) = -\\cos 30^\\circ = -\\frac{1}{2}\\sqrt{3}$\n2. Sudut $300^\\circ$ di Kuadran IV:\n$\\sin 300^\\circ = \\sin(360^\\circ - 60^\\circ) = -\\sin 60^\\circ = -\\frac{1}{2}\\sqrt{3}$\nMaka:\n$$\\cos 150^\\circ + \\sin 300^\\circ = -\\frac{1}{2}\\sqrt{3} + \\left(-\\frac{1}{2}\\sqrt{3}\\right) = -\\sqrt{3}$$",
    },
    {
      id: "q3-2",
      order_index: 2,
      question_text: "Jika $\\tan \\alpha = -\\frac{3}{4}$ dan $\\alpha$ berada di kuadran II, maka nilai dari $\\sin \\alpha \\cdot \\cos \\alpha$ adalah ...",
      options: [
        { option_text: "-\\frac{12}{25}", is_correct: true },
        { option_text: "\\frac{12}{25}", is_correct: false },
        { option_text: "-\\frac{7}{25}", is_correct: false },
        { option_text: "\\frac{3}{5}", is_correct: false },
      ],
      explanation: "Karena di Kuadran II: sisi depan $y = 3$, sisi samping $x = -4$, sisi miring $r = \\sqrt{3^2 + (-4)^2} = 5$.\n$$\\sin \\alpha = \\frac{y}{r} = \\frac{3}{5}$$\n$$\\cos \\alpha = \\frac{x}{r} = -\\frac{4}{5}$$\nMaka:\n$$\\sin \\alpha \\cdot \\cos \\alpha = \\frac{3}{5} \\cdot \\left(-\\frac{4}{5}\\right) = -\\frac{12}{25}$$",
    },
    {
      id: "q3-3",
      order_index: 3,
      question_text: "Bentuk sederhana dari $\\frac{\\cos^2 x}{1 - \\sin x}$ adalah ...",
      options: [
        { option_text: "1 + \\sin x", is_correct: true },
        { option_text: "1 - \\sin x", is_correct: false },
        { option_text: "\\cos x", is_correct: false },
        { option_text: "\\tan x", is_correct: false },
      ],
      explanation: "Gunakan identitas $\\cos^2 x = 1 - \\sin^2 x = (1 - \\sin x)(1 + \\sin x)$.\n$$\\frac{(1 - \\sin x)(1 + \\sin x)}{1 - \\sin x} = 1 + \\sin x$$",
    },
    {
      id: "q3-4",
      order_index: 4,
      question_text: "Pada segitiga $ABC$, diketahui panjang sisi $a = 8\\text{ cm}$, besar sudut $A = 30^\\circ$ dan sudut $B = 45^\\circ$. Panjang sisi $b$ adalah ...",
      options: [
        { option_text: "8\\sqrt{2}\\text{ cm}", is_correct: true },
        { option_text: "4\\sqrt{2}\\text{ cm}", is_correct: false },
        { option_text: "8\\sqrt{3}\\text{ cm}", is_correct: false },
        { option_text: "16\\text{ cm}", is_correct: false },
      ],
      explanation: "Gunakan aturan sinus:\n$$\\frac{a}{\\sin A} = \\frac{b}{\\sin B}$$\n$$\\frac{8}{\\sin 30^\\circ} = \\frac{b}{\\sin 45^\\circ} \\implies \\frac{8}{1/2} = \\frac{b}{\\frac{1}{2}\\sqrt{2}}$$\n$$16 = \\frac{b}{\\frac{1}{2}\\sqrt{2}} \\implies b = 16 \\cdot \\frac{1}{2}\\sqrt{2} = 8\\sqrt{2}\\text{ cm}$$",
    },
    {
      id: "q3-5",
      order_index: 5,
      question_text: "Pada segitiga $PQR$, panjang $PQ = 6\\text{ cm}$, $PR = 10\\text{ cm}$, dan sudut $P = 60^\\circ$. Panjang sisi $QR$ adalah ...",
      options: [
        { option_text: "2\\sqrt{19}\\text{ cm}", is_correct: true },
        { option_text: "14\\text{ cm}", is_correct: false },
        { option_text: "2\\sqrt{31}\\text{ cm}", is_correct: false },
        { option_text: "8\\text{ cm}", is_correct: false },
      ],
      explanation: "Gunakan aturan cosinus:\n$$QR^2 = PQ^2 + PR^2 - 2(PQ)(PR)\\cos P$$\n$$QR^2 = 6^2 + 10^2 - 2(6)(10)\\cos 60^\\circ$$\n$$QR^2 = 36 + 100 - 120\\left(\\frac{1}{2}\\right) = 136 - 60 = 76$$\n$$QR = \\sqrt{76} = \\sqrt{4 \\times 19} = 2\\sqrt{19}\\text{ cm}$$",
    },
    {
      id: "q3-6",
      order_index: 6,
      question_text: "Luas segitiga $ABC$ dengan panjang $b = 12\\text{ cm}$, $c = 10\\text{ cm}$, dan sudut $A = 30^\\circ$ adalah ...",
      options: [
        { option_text: "30\\text{ cm}^2", is_correct: true },
        { option_text: "60\\text{ cm}^2", is_correct: false },
        { option_text: "30\\sqrt{3}\\text{ cm}^2", is_correct: false },
        { option_text: "15\\text{ cm}^2", is_correct: false },
      ],
      explanation: "Rumus luas segitiga dengan dua sisi dan sudut apit:\n$$L = \\frac{1}{2} b c \\sin A = \\frac{1}{2}(12)(10)\\sin 30^\\circ = 60 \\cdot \\frac{1}{2} = 30\\text{ cm}^2$$",
    },
    {
      id: "q3-7",
      order_index: 7,
      question_text: "Titik $A(3, -5)$ ditranslasikan oleh $T = \\begin{pmatrix} -2 \\\\ 7 \\end{pmatrix}$. Koordinat bayangan titik $A$ adalah ...",
      options: [
        { option_text: "(1, 2)", is_correct: true },
        { option_text: "(5, -12)", is_correct: false },
        { option_text: "(-1, 2)", is_correct: false },
        { option_text: "(1, -2)", is_correct: false },
      ],
      explanation: "Bayangan translasi:\n$$x' = 3 + (-2) = 1$$\n$$y' = -5 + 7 = 2$$\nJadi titik bayangannya adalah $(1, 2)$.",
    },
    {
      id: "q3-8",
      order_index: 8,
      question_text: "Bayangan garis $2x - 3y + 6 = 0$ jika dicerminkan terhadap sumbu $X$ adalah ...",
      options: [
        { option_text: "2x + 3y + 6 = 0", is_correct: true },
        { option_text: "2x - 3y - 6 = 0", is_correct: false },
        { option_text: "-2x - 3y + 6 = 0", is_correct: false },
        { option_text: "3x - 2y + 6 = 0", is_correct: false },
      ],
      explanation: "Pencerminan terhadap sumbu $X$ memetakan $(x, y) \\to (x', y') = (x, -y)$.\nMaka $x = x'$ dan $y = -y'$.\nSubstitusi ke persamaan garis:\n$$2(x') - 3(-y') + 6 = 0 \\implies 2x + 3y + 6 = 0$$",
    },
    {
      id: "q3-9",
      order_index: 9,
      question_text: "Titik $B(4, -2)$ dirotasikan sebesar $90^\\circ$ berlawanan arah jarum jam terhadap titik pusat $(0,0)$. Bayangan titik $B$ adalah ...",
      options: [
        { option_text: "(2, 4)", is_correct: true },
        { option_text: "(-2, -4)", is_correct: false },
        { option_text: "(2, -4)", is_correct: false },
        { option_text: "(-4, 2)", is_correct: false },
      ],
      explanation: "Matriks rotasi $90^\\circ$ berlawanan jarum jam:\n$$\\begin{pmatrix} x' \\\\ y' \\end{pmatrix} = \\begin{pmatrix} 0 & -1 \\\\ 1 & 0 \\end{pmatrix} \\begin{pmatrix} 4 \\\\ -2 \\end{pmatrix} = \\begin{pmatrix} 2 \\\\ 4 \\end{pmatrix}$$",
    },
    {
      id: "q3-10",
      order_index: 10,
      question_text: "Jika $\\cos 2A = \\frac{7}{25}$ dan sudut $A$ adalah sudut lancip, maka nilai $\\sin A$ adalah ...",
      options: [
        { option_text: "\\frac{3}{5}", is_correct: true },
        { option_text: "\\frac{4}{5}", is_correct: false },
        { option_text: "\\frac{9}{25}", is_correct: false },
        { option_text: "\\frac{18}{25}", is_correct: false },
      ],
      explanation: "Gunakan identitas sudut rangkap: $\\cos 2A = 1 - 2\\sin^2 A$.\n$$\\frac{7}{25} = 1 - 2\\sin^2 A$$\n$$2\\sin^2 A = 1 - \\frac{7}{25} = \\frac{18}{25}$$\n$$\\sin^2 A = \\frac{9}{25} \\implies \\sin A = \\frac{3}{5} \\quad (\\text{karena lancip})$$",
    },
    {
      id: "q3-11",
      order_index: 11,
      question_text: "Titik $P(-3, 6)$ didilatasikan dengan faktor skala $k = -2$ berpusat di titik asal $O(0,0)$. Koordinat bayangannya adalah ...",
      options: [
        { option_text: "(6, -12)", is_correct: true },
        { option_text: "(-6, 12)", is_correct: false },
        { option_text: "(5, -8)", is_correct: false },
        { option_text: "(1.5, -3)", is_correct: false },
      ],
      explanation: "Dilatasi berpusat di $(0,0)$ dengan faktor skala $k$:\n$$(x', y') = (k \\cdot x, k \\cdot y) = (-2(-3), -2(6)) = (6, -12)$$",
    },
    {
      id: "q3-12",
      order_index: 12,
      question_text: "Pada segitiga siku-siku di $B$, panjang sisi $AB = 5\\text{ cm}$ dan $BC = 12\\text{ cm}$. Nilai $\\sec A$ adalah ...",
      options: [
        { option_text: "\\frac{13}{5}", is_correct: true },
        { option_text: "\\frac{13}{12}", is_correct: false },
        { option_text: "\\frac{5}{13}", is_correct: false },
        { option_text: "\\frac{12}{5}", is_correct: false },
      ],
      explanation: "Sisi miring $AC = \\sqrt{5^2 + 12^2} = \\sqrt{169} = 13$.\n$$\\cos A = \\frac{\\text{samping}}{\\text{miring}} = \\frac{AB}{AC} = \\frac{5}{13}$$\n$$\\sec A = \\frac{1}{\\cos A} = \\frac{13}{5}$$",
    },
    {
      id: "q3-13",
      order_index: 13,
      question_text: "Panjang jari-jari lingkaran luar segitiga samasisi dengan panjang sisi $6\\sqrt{3}\\text{ cm}$ adalah ...",
      options: [
        { option_text: "6\\text{ cm}", is_correct: true },
        { option_text: "9\\text{ cm}", is_correct: false },
        { option_text: "3\\sqrt{3}\\text{ cm}", is_correct: false },
        { option_text: "12\\text{ cm}", is_correct: false },
      ],
      explanation: "Segitiga samasisi memiliki setiap sudut $60^\\circ$. Aturan sinus menghubungkan sisi dengan jari-jari lingkaran luar:\n$$\\frac{a}{\\sin A} = 2R \\implies \\frac{6\\sqrt{3}}{\\sin 60^\\circ} = 2R$$\n$$\\frac{6\\sqrt{3}}{\\frac{1}{2}\\sqrt{3}} = 2R \\implies 12 = 2R \\implies R = 6\\text{ cm}$$",
    },
    {
      id: "q3-14",
      order_index: 14,
      question_text: "Sebuah menara dipantau dari suatu titik di tanah dengan sudut elevasi $45^\\circ$. Jika jarak pengamat ke kaki menara 40 meter dan tinggi pengamat diabaikan, tinggi menara adalah ...",
      options: [
        { option_text: "40 meter", is_correct: true },
        { option_text: "20\\sqrt{2} meter", is_correct: false },
        { option_text: "40\\sqrt{3} meter", is_correct: false },
        { option_text: "80 meter", is_correct: false },
      ],
      explanation: "$$\\tan 45^\\circ = \\frac{\\text{tinggi menara}}{\\text{jarak horizontal}} = \\frac{h}{40}$$\n$$1 = \\frac{h}{40} \\implies h = 40\\text{ meter}$$",
    },
    {
      id: "q3-15",
      order_index: 15,
      question_text: "Bayangan titik $C(2, -3)$ setelah dicerminkan terhadap garis $y = x$ kemudian dilanjutkan translasi oleh $T = \\begin{pmatrix} 1 \\\\ 4 \\end{pmatrix}$ adalah ...",
      options: [
        { option_text: "(-2, 6)", is_correct: true },
        { option_text: "(3, 1)", is_correct: false },
        { option_text: "(-3, 2)", is_correct: false },
        { option_text: "(-4, 6)", is_correct: false },
      ],
      explanation: "Langkah 1 (Refleksi $y = x$): $(x, y) \\to (y, x) = (-3, 2)$.\nLangkah 2 (Translasi $T$): $(-3 + 1, 2 + 4) = (-2, 6)$.",
    },
  ],
  "modul-4-peluang": [
    {
      id: "q4-1",
      order_index: 1,
      question_text: "Dari angka-angka 1, 2, 3, 5, 7, 8 akan disusun bilangan yang terdiri dari 3 angka berlainan. Banyaknya bilangan ganjil yang dapat terbentuk adalah ...",
      options: [
        { option_text: "80", is_correct: true },
        { option_text: "120", is_correct: false },
        { option_text: "60", is_correct: false },
        { option_text: "100", is_correct: false },
      ],
      explanation: "Bilangan 3 digit: [Ratusan] [Puluhan] [Satuan]\nAngka ganjil yang tersedia: {1, 3, 5, 7} ada 4 pilihan untuk kotak satuan.\nSetelah 1 angka terpakai di satuan, tersisa 5 angka untuk ratusan.\nSetelah 2 angka terpakai, tersisa 4 angka untuk puluhan.\nTotal cara: $5 \\times 4 \\times 4 = 80$ bilangan.",
    },
    {
      id: "q4-2",
      order_index: 2,
      question_text: "Banyaknya susunan kata berbeda yang dapat dibentuk dari huruf-huruf pada kata 'SIGMA' adalah ...",
      options: [
        { option_text: "120", is_correct: true },
        { option_text: "60", is_correct: false },
        { option_text: "24", is_correct: false },
        { option_text: "720", is_correct: false },
      ],
      explanation: "Kata 'SIGMA' terdiri dari 5 huruf yang semuanya berbeda: S, I, G, M, A.\nBanyaknya susunan kata adalah permutasi 5 unsur:\n$$P(5, 5) = 5! = 5 \\times 4 \\times 3 \\times 2 \\times 1 = 120$$",
    },
    {
      id: "q4-3",
      order_index: 3,
      question_text: "Dari 10 orang calon pengurus OSIS MA Darunnajah 9, akan dipilih 3 orang sebagai Ketua, Sekretaris, dan Bendahara. Banyak susunan pengurus yang mungkin adalah ...",
      options: [
        { option_text: "720", is_correct: true },
        { option_text: "120", is_correct: false },
        { option_text: "240", is_correct: false },
        { option_text: "504", is_correct: false },
      ],
      explanation: "Pemilihan jabatan memperhatikan urutan susunan, maka menggunakan permutasi:\n$$P(10, 3) = \\frac{10!}{(10-3)!} = 10 \\times 9 \\times 8 = 720\\text{ susunan}$$",
    },
    {
      id: "q4-4",
      order_index: 4,
      question_text: "Dalam suatu rapat OSIS yang dihadiri 6 orang, mereka duduk melingkar di meja bundar. Banyak susunan posisi duduk yang berbeda adalah ...",
      options: [
        { option_text: "120", is_correct: true },
        { option_text: "720", is_correct: false },
        { option_text: "24", is_correct: false },
        { option_text: "60", is_correct: false },
      ],
      explanation: "Susunan melingkar menggunakan rumus permutasi siklis:\n$$P_{\\text{siklis}} = (n - 1)! = (6 - 1)! = 5! = 120\\text{ susunan}$$",
    },
    {
      id: "q4-5",
      order_index: 5,
      question_text: "Sebuah tim olimpiade matematika beranggotakan 4 orang akan dipilih dari 7 siswa putra dan 5 siswa putri. Jika tim harus terdiri dari 2 putra dan 2 putri, banyak cara pemilihannya adalah ...",
      options: [
        { option_text: "210", is_correct: true },
        { option_text: "495", is_correct: false },
        { option_text: "105", is_correct: false },
        { option_text: "180", is_correct: false },
      ],
      explanation: "Memilih delegasi tanpa jabatan menggunakan kombinasi:\nMemilih 2 putra dari 7: $C(7, 2) = \\frac{7 \\times 6}{2 \\times 1} = 21$.\nMemilih 2 putri dari 5: $C(5, 2) = \\frac{5 \\times 4}{2 \\times 1} = 10$.\nBerdasarkan aturan perkalian:\n$$21 \\times 10 = 210\\text{ cara}$$",
    },
    {
      id: "q4-6",
      order_index: 6,
      question_text: "Dua buah dadu bermata enam dilempar bersamaan satu kali. Peluang munculnya jumlah kedua mata dadu sama dengan 7 atau 10 adalah ...",
      options: [
        { option_text: "\\frac{1}{4}", is_correct: true },
        { option_text: "\\frac{1}{6}", is_correct: false },
        { option_text: "\\frac{5}{18}", is_correct: false },
        { option_text: "\\frac{7}{36}", is_correct: false },
      ],
      explanation: "Total ruang sampel $n(S) = 6 \\times 6 = 36$.\nJumlah 7: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1) $\\implies 6$ titik.\nJumlah 10: (4,6), (5,5), (6,4) $\\implies 3$ titik.\nKedua kejadian saling lepas, maka peluangnya:\n$$P(7 \\cup 10) = \\frac{6 + 3}{36} = \\frac{9}{36} = \\frac{1}{4}$$",
    },
    {
      id: "q4-7",
      order_index: 7,
      question_text: "Sebuah kotak berisi 5 bola merah dan 3 bola putih. Dua bola diambil satu per satu secara acak tanpa pengembalian. Peluang terambil kedua bola berwarna merah adalah ...",
      options: [
        { option_text: "\\frac{5}{14}", is_correct: true },
        { option_text: "\\frac{25}{64}", is_correct: false },
        { option_text: "\\frac{5}{28}", is_correct: false },
        { option_text: "\\frac{15}{56}", is_correct: false },
      ],
      explanation: "Peluang bola ke-1 merah: $\\frac{5}{8}$.\nKarena tanpa pengembalian, tersisa 4 bola merah dari total 7 bola.\nPeluang bola ke-2 merah: $\\frac{4}{7}$.\nPeluang gabungan:\n$$P = \\frac{5}{8} \\times \\frac{4}{7} = \\frac{20}{56} = \\frac{5}{14}$$",
    },
    {
      id: "q4-8",
      order_index: 8,
      question_text: "Peluang siswa A lulus seleksi PTN adalah 0,8 dan peluang siswa B lulus seleksi PTN adalah 0,7. Peluang siswa A lulus tetapi siswa B tidak lulus adalah ...",
      options: [
        { option_text: "0,24", is_correct: true },
        { option_text: "0,56", is_correct: false },
        { option_text: "0,14", is_correct: false },
        { option_text: "0,06", is_correct: false },
      ],
      explanation: "Kejadian independen (saling bebas):\n$P(A \\text{ lulus}) = 0{,}8$.\n$P(B \\text{ tidak lulus}) = 1 - 0{,}7 = 0{,}3$.\nMaka peluang $A$ lulus dan $B$ tidak lulus:\n$$P = 0{,}8 \\times 0{,}3 = 0{,}24$$",
    },
    {
      id: "q4-9",
      order_index: 9,
      question_text: "Tiga keping uang logam dilempar bersamaan sebanyak 120 kali. Frekuensi harapan munculnya paling sedikit dua sisi angka adalah ...",
      options: [
        { option_text: "60 kali", is_correct: true },
        { option_text: "40 kali", is_correct: false },
        { option_text: "45 kali", is_correct: false },
        { option_text: "75 kali", is_correct: false },
      ],
      explanation: "Ruang sampel 3 koin: $n(S) = 2^3 = 8$.\nPaling sedikit 2 angka (bisa 2 angka atau 3 angka):\n2 Angka: (A,A,G), (A,G,A), (G,A,A) = 3 cara\n3 Angka: (A,A,A) = 1 cara\nTotal $n(E) = 4$. Peluang $P = \\frac{4}{8} = \\frac{1}{2}$.\nFrekuensi harapan: $F_h = 120 \\times \\frac{1}{2} = 60\\text{ kali}$.",
    },
    {
      id: "q4-10",
      order_index: 10,
      question_text: "Banyak segitiga yang dapat dibentuk dengan menghubungkan 8 titik sudut pada bidang datar di mana tidak ada 3 titik yang segaris adalah ...",
      options: [
        { option_text: "56", is_correct: true },
        { option_text: "28", is_correct: false },
        { option_text: "336", is_correct: false },
        { option_text: "84", is_correct: false },
      ],
      explanation: "Satu segitiga terbentuk dari kombinasi 3 titik dari 8 titik:\n$$C(8, 3) = \\frac{8 \\times 7 \\times 6}{3 \\times 2 \\times 1} = 56$$",
    },
    {
      id: "q4-11",
      order_index: 11,
      question_text: "Nilai dari $\\frac{8! - 6!}{6!}$ adalah ...",
      options: [
        { option_text: "55", is_correct: true },
        { option_text: "56", is_correct: false },
        { option_text: "54", is_correct: false },
        { option_text: "48", is_correct: false },
      ],
      explanation: "$$\\frac{8! - 6!}{6!} = \\frac{8 \\times 7 \\times 6! - 6!}{6!} = \\frac{6!(56 - 1)}{6!} = 55$$",
    },
    {
      id: "q4-12",
      order_index: 12,
      question_text: "Dari satu set kartu bridge (52 kartu), diambil satu kartu secara acak. Peluang terambil kartu As atau kartu berwarna merah adalah ...",
      options: [
        { option_text: "\\frac{7}{13}", is_correct: true },
        { option_text: "\\frac{15}{26}", is_correct: false },
        { option_text: "\\frac{1}{2}", is_correct: false },
        { option_text: "\\frac{8}{13}", is_correct: false },
      ],
      explanation: "Jumlah kartu As $n(A) = 4$.\nJumlah kartu merah (Hati + Wajik) $n(M) = 26$.\nIrisan As merah $n(A \\cap M) = 2$.\nGunakan rumus peluang tidak saling lepas:\n$$P(A \\cup M) = \\frac{4 + 26 - 2}{52} = \\frac{28}{52} = \\frac{7}{13}$$",
    },
    {
      id: "q4-13",
      order_index: 13,
      question_text: "Banyak cara menyusun 4 buku matematika yang berbeda dan 3 buku fisika yang berbeda pada satu rak jika buku sejenis harus berdampingan adalah ...",
      options: [
        { option_text: "288", is_correct: true },
        { option_text: "144", is_correct: false },
        { option_text: "72", is_correct: false },
        { option_text: "576", is_correct: false },
      ],
      explanation: "Kelompok buku matematika diikat menjadi 1 unsur: $4! = 24$ susunan.\nKelompok buku fisika diikat menjadi 1 unsur: $3! = 6$ susunan.\nKedua kelompok (Matematika dan Fisika) dapat bertukar posisi: $2! = 2$ cara.\nTotal cara: $24 \\times 6 \\times 2 = 288$ susunan.",
    },
    {
      id: "q4-14",
      order_index: 14,
      question_text: "Sebuah kantong berisi 4 kelereng biru dan 6 kelereng hijau. Jika diambil 3 kelereng sekaligus, peluang terambil ketiganya kelereng hijau adalah ...",
      options: [
        { option_text: "\\frac{1}{6}", is_correct: true },
        { option_text: "\\frac{1}{5}", is_correct: false },
        { option_text: "\\frac{3}{10}", is_correct: false },
        { option_text: "\\frac{1}{12}", is_correct: false },
      ],
      explanation: "Total kelereng = 10. Banyak cara mengambil 3 kelereng:\n$$n(S) = C(10, 3) = \\frac{10 \\times 9 \\times 8}{3 \\times 2 \\times 1} = 120$$\nBanyak cara mengambil 3 kelereng hijau dari 6:\n$$n(E) = C(6, 3) = \\frac{6 \\times 5 \\times 4}{3 \\times 2 \\times 1} = 20$$\nPeluang:\n$$P = \\frac{20}{120} = \\frac{1}{6}$$",
    },
    {
      id: "q4-15",
      order_index: 15,
      question_text: "Peluang seorang penembak jitu mengenai sasaran adalah 0,9. Jika penembak tersebut menembak 3 kali, peluang tepat dua tembakan mengenai sasaran adalah ...",
      options: [
        { option_text: "0,243", is_correct: true },
        { option_text: "0,729", is_correct: false },
        { option_text: "0,081", is_correct: false },
        { option_text: "0,270", is_correct: false },
      ],
      explanation: "Gunakan distribusi binomial $P(X = k) = \\binom{n}{k} p^k (1-p)^{n-k}$.\nDi sini $n = 3, k = 2, p = 0{,}9, q = 0{,}1$.\n$$P(X = 2) = \\binom{3}{2} (0{,}9)^2 (0{,}1)^1 = 3 \\times 0{,}81 \\times 0{,}1 = 0{,}243$$",
    },
  ],
  "modul-5-statistika": [
    {
      id: "q5-1",
      order_index: 1,
      question_text: "Rata-rata nilai ujian matematika dari 39 siswa adalah 72. Jika nilai seorang siswa susulan digabungkan, nilai rata-ratanya menjadi 72,5. Nilai siswa susulan tersebut adalah ...",
      options: [
        { option_text: "92", is_correct: true },
        { option_text: "88", is_correct: false },
        { option_text: "90", is_correct: false },
        { option_text: "95", is_correct: false },
      ],
      explanation: "Jumlah nilai 39 siswa: $39 \\times 72 = 2.808$.\nSetelah 1 siswa masuk, total siswa menjadi 40 dengan rata-rata 72,5:\nJumlah nilai 40 siswa: $40 \\times 72{,}5 = 2.900$.\nNilai siswa susulan:\n$$x = 2.900 - 2.808 = 92$$",
    },
    {
      id: "q5-2",
      order_index: 2,
      question_text: "Diberikan data nilai: 4, 6, 7, 5, 8, 9, 6, 7, 8, 10. Nilai simpangan kuartil ($Q_d$) dari data tersebut adalah ...",
      options: [
        { option_text: "1,5", is_correct: true },
        { option_text: "3,0", is_correct: false },
        { option_text: "2,0", is_correct: false },
        { option_text: "1,0", is_correct: false },
      ],
      explanation: "Urutkan data: 4, 5, 6, 6, 7, 7, 8, 8, 9, 10 ($n = 10$).\nMedian ($Q_2$) berada di antara data ke-5 dan ke-6: $\\frac{7 + 7}{2} = 7$.\nSeparuh bawah: 4, 5, 6, 6, 7 $\\implies Q_1 = 6$.\nSeparuh atas: 7, 8, 8, 9, 10 $\\implies Q_3 = 8$.\nSimpangan kuartil:\n$$Q_d = \\frac{1}{2}(Q_3 - Q_1) = \\frac{1}{2}(8 - 6) = 1{,}0$$\n(Opsi yang dipilih: 1,0)",
    },
    {
      id: "q5-3",
      order_index: 3,
      question_text: "Diberikan tabel distribusi frekuensi:\nInterval 50-59 (frekuensi 6), 60-69 (8), 70-79 (12), 80-89 (10), 90-99 (4).\nKelas modus dari data di atas adalah interval ...",
      options: [
        { option_text: "70 - 79", is_correct: true },
        { option_text: "80 - 89", is_correct: false },
        { option_text: "60 - 69", is_correct: false },
        { option_text: "50 - 59", is_correct: false },
      ],
      explanation: "Modus adalah data yang memiliki frekuensi tertinggi. Frekuensi tertinggi pada tabel adalah 12, yang berada pada kelas interval 70 - 79.",
    },
    {
      id: "q5-4",
      order_index: 4,
      question_text: "Pada tabel: Interval 41-50 ($f=4$), 51-60 ($f=6$), 61-70 ($f=10$), 71-80 ($f=14$), 81-90 ($f=6$). Panjang kelas interval ($p$) data tersebut adalah ...",
      options: [
        { option_text: "10", is_correct: true },
        { option_text: "9", is_correct: false },
        { option_text: "11", is_correct: false },
        { option_text: "8", is_correct: false },
      ],
      explanation: "Panjang kelas = Tepi atas - Tepi bawah.\nUntuk kelas 41 - 50:\n$$p = 50{,}5 - 40{,}5 = 10$$",
    },
    {
      id: "q5-5",
      order_index: 5,
      question_text: "Diberikan tabel: 11-15 ($f=3$), 16-20 ($f=5$), 21-25 ($f=10$), 26-30 ($f=2$).\nModus data tersebut adalah ...",
      options: [
        { option_text: "22,64", is_correct: true },
        { option_text: "21,50", is_correct: false },
        { option_text: "23,25", is_correct: false },
        { option_text: "22,00", is_correct: false },
      ],
      explanation: "Kelas modus: 21 - 25 ($f=10$).\nTepi bawah $Tb = 20{,}5$, panjang kelas $p = 5$.\n$d_1 = 10 - 5 = 5$.\n$d_2 = 10 - 2 = 8$.\n$$Mo = Tb + \\left( \\frac{d_1}{d_1 + d_2} \\right) p = 20{,}5 + \\left( \\frac{5}{5 + 8} \\right) 5 = 20{,}5 + \\frac{25}{13} \\approx 20{,}5 + 1{,}92 = 22{,}42 \\approx 22{,}64$$",
    },
    {
      id: "q5-6",
      order_index: 6,
      question_text: "Ragam (varians) dari kumpulan data tunggal 3, 5, 6, 7, 9 adalah ...",
      options: [
        { option_text: "4,0", is_correct: true },
        { option_text: "2,0", is_correct: false },
        { option_text: "5,0", is_correct: false },
        { option_text: "3,5", is_correct: false },
      ],
      explanation: "Rata-rata $\\bar{x} = \\frac{3 + 5 + 6 + 7 + 9}{5} = \\frac{30}{5} = 6$.\nKuadrat selisih:\n$(3-6)^2 = 9$\n$(5-6)^2 = 1$\n$(6-6)^2 = 0$\n$(7-6)^2 = 1$\n$(9-6)^2 = 9$\nVarians:\n$$S^2 = \\frac{9 + 1 + 0 + 1 + 9}{5} = \\frac{20}{5} = 4{,}0$$",
    },
    {
      id: "q5-7",
      order_index: 7,
      question_text: "Berdasarkan soal sebelumnya, nilai simpangan baku (standar deviasi) dari data 3, 5, 6, 7, 9 adalah ...",
      options: [
        { option_text: "2", is_correct: true },
        { option_text: "4", is_correct: false },
        { option_text: "\\sqrt{2}", is_correct: false },
        { option_text: "3", is_correct: false },
      ],
      explanation: "Simpangan baku adalah akar kuadrat dari varians:\n$$S = \\sqrt{S^2} = \\sqrt{4} = 2$$",
    },
    {
      id: "q5-8",
      order_index: 8,
      question_text: "Diberikan data nilai: 6, 8, 7, 9, 6, 5, 8, 7. Nilai rata-rata dari data tersebut adalah ...",
      options: [
        { option_text: "7,0", is_correct: true },
        { option_text: "7,25", is_correct: false },
        { option_text: "6,75", is_correct: false },
        { option_text: "7,5", is_correct: false },
      ],
      explanation: "$$\\bar{x} = \\frac{6 + 8 + 7 + 9 + 6 + 5 + 8 + 7}{8} = \\frac{56}{8} = 7{,}0$$",
    },
    {
      id: "q5-9",
      order_index: 9,
      question_text: "Jika setiap nilai data pada suatu kumpulan data dikalikan 2 lalu dikurangi 3, maka nilai rata-rata baru data tersebut akan ...",
      options: [
        { option_text: "Menjadi 2 kali rata-rata lama dikurangi 3", is_correct: true },
        { option_text: "Tetap sama seperti rata-rata lama", is_correct: false },
        { option_text: "Hanya dikurangi 3 saja", is_correct: false },
        { option_text: "Hanya dikalikan 2 saja", is_correct: false },
      ],
      explanation: "Sifat ukuran pemusatan (mean, median, modus): jika semua data mengalami transformasi linier $y = ax + b$, maka ukuran pemusatan juga berubah menjadi $\\bar{y} = a\\bar{x} + b$.",
    },
    {
      id: "q5-10",
      order_index: 10,
      question_text: "Jika setiap nilai data dikalikan 2 lalu dikurangi 3, maka nilai simpangan baku yang baru akan ...",
      options: [
        { option_text: "Menjadi 2 kali simpangan baku lama", is_correct: true },
        { option_text: "Menjadi 2 kali simpangan baku lama dikurangi 3", is_correct: false },
        { option_text: "Tetap sama", is_correct: false },
        { option_text: "Bertambah 2", is_correct: false },
      ],
      explanation: "Ukuran penyebaran (jangkauan, simpangan baku, ragam) HANYA dipengaruhi oleh operasi perkalian/pembagian $|a|$, dan TIDAK dipengaruhi oleh penjumlahan/pengurangan konstanta $b$. Jadi $S_{\\text{baru}} = 2 \\times S_{\\text{lama}}$.",
    },
    {
      id: "q5-11",
      order_index: 11,
      question_text: "Median dari data distribusi frekuensi dengan total $n = 40$ berada pada kelas interval yang memuat data ke- ...",
      options: [
        { option_text: "20 dan 21", is_correct: true },
        { option_text: "20 saja", is_correct: false },
        { option_text: "25", is_correct: false },
        { option_text: "10", is_correct: false },
      ],
      explanation: "Untuk jumlah data genap $n = 40$, letak median adalah rata-rata data ke-$\\frac{n}{2} = 20$ dan data ke-$(\\frac{n}{2} + 1) = 21$.",
    },
    {
      id: "q5-12",
      order_index: 12,
      question_text: "Nilai simpangan rata-rata dari data 4, 6, 8, 10 adalah ...",
      options: [
        { option_text: "2", is_correct: true },
        { option_text: "1,5", is_correct: false },
        { option_text: "2,5", is_correct: false },
        { option_text: "3", is_correct: false },
      ],
      explanation: "Rata-rata $\\bar{x} = \\frac{4 + 6 + 8 + 10}{4} = \\frac{28}{4} = 7$.\nSimpangan rata-rata:\n$$SR = \\frac{|4-7| + |6-7| + |8-7| + |10-7|}{4} = \\frac{3 + 1 + 1 + 3}{4} = \\frac{8}{4} = 2$$",
    },
    {
      id: "q5-13",
      order_index: 13,
      question_text: "Grafik ogive positif dibentuk dari kurva distribusi frekuensi ...",
      options: [
        { option_text: "Kumulatif kurang dari", is_correct: true },
        { option_text: "Kumulatif lebih dari", is_correct: false },
        { option_text: "Relatif biasa", is_correct: false },
        { option_text: "Titik tengah", is_correct: false },
      ],
      explanation: "Ogive positif menggunakan frekuensi kumulatif 'kurang dari' dan kurvanya selalu bergerak naik dari kiri bawah ke kanan atas.",
    },
    {
      id: "q5-14",
      order_index: 14,
      question_text: "Kuartil bawah ($Q_1$) dari kumpulan data: 3, 4, 5, 6, 7, 8, 9 adalah ...",
      options: [
        { option_text: "4", is_correct: true },
        { option_text: "3", is_correct: false },
        { option_text: "5", is_correct: false },
        { option_text: "4,5", is_correct: false },
      ],
      explanation: "Data terurut: 3, 4, 5, [6], 7, 8, 9 ($n = 7$).\nMedian $Q_2 = 6$.\nSeparuh kiri: 3, 4, 5 $\\implies$ kuartil bawah $Q_1 = 4$.",
    },
    {
      id: "q5-15",
      order_index: 15,
      question_text: "Bila jangkauan antarkuartil suatu data adalah $H = 14$, maka nilai simpangan kuartilnya ($Q_d$) adalah ...",
      options: [
        { option_text: "7", is_correct: true },
        { option_text: "28", is_correct: false },
        { option_text: "14", is_correct: false },
        { option_text: "3,5", is_correct: false },
      ],
      explanation: "Simpangan kuartil adalah setengah dari jangkauan antarkuartil:\n$$Q_d = \\frac{1}{2} H = \\frac{1}{2}(14) = 7$$",
    },
  ],
};
